REGIONS = [
    "US East (Ohio)",
    "US East (N. Virginia)",
    "US West (N. California)",
    "US West (Oregon)",
    "Asia Pacific (Hong Kong)",
    "Asia Pacific (Mumbai)",
    "Asia Pacific (Osaka-Local)",
    "Asia Pacific (Seoul)",
    "Asia Pacific (Singapore)",
    "Asia Pacific (Sydney)",
    "Asia Pacific (Tokyo)",
    "Canada (Central)",
    "China (Beijing)",
    "China (Ningxia)",
    "EU (Frankfurt)",
    "EU (Ireland)",
    "EU (London)",
    "EU (Paris)",
    "EU (Stockholm)",
    "Middle East (Bahrain)",
    "South America (Sao Paulo)",
]
